MMORPG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', include('MMORPG_Board.urls')),
    path('admin/', admin.site.urls),
    path('MMORPG_Account/', include('MMORPG_Account.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MMORPG_Board/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class BaseModel(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    dateCreation = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        abstract = True

class Post(BaseModel):
    CAT = (('tanks', 'Танки'),
           ('healers', 'Хилы'),
           ('damage_dealers', 'ДД'),
           ('dealers', 'Торговцы'),
           ('gildmasters', 'Гилдмастеры'),
           ('quest_givers', 'Квестгиверы'),
           ('blacksmiths', 'Кузнецы'),
           ('tanners', 'Кожевники'),
           ('potion_makers', 'Зельевары'),
           ('spell_masters', 'Мастера заклинаний'))
    category = models.CharField(max_length=15, choices=CAT, verbose_name='Категория')
    title = models.CharField(max_length=256, verbose_name='Заголовок')
    text = RichTextField(verbose_name='Текст объявления')

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

class Response(BaseModel):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='Пост')
    text = models.TextField(verbose_name='Текст')
    status = models.BooleanField(default=False, verbose_name='Статус')

    class Meta:
        verbose_name = 'Отклик'
        verbose_name_plural = 'Отклики'

templates/create_publication.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Create{% endblock title %}
{% load static %}
{% block content %}
    <br>
    <h3>Новое объявление</h3><br>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
		<input class="btn btn-secondary" type="submit" value="Сохранить">
	</form><br>
    <input type=button value="Назад" class="btn btn-secondary" onClick="javascript:history.go(-1);">
{% endblock content %}

templates/default.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <meta name="description" content="" />
        <meta name="author" content="" />

        <title>Доска обьявлений MMORPG {% block title %} {% endblock title %}</title>

        <!-- Bootstrap core CSS -->
        <link
            href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}"
            rel="stylesheet"
        />
        <style>
          body {
            background-color: khaki;
          }
        </style>
    </head>

    <body>
        <!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary static-top">
    <div class="container">
        <a class="navbar-brand" href="/">Доска объявлений MMORPG</a>

        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarResponsive"
            aria-controls="navbarResponsive"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Объявления <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'responses' %}">Отклики</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Личный кабинет
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'profile_accounts' %}">Профиль</a>
                            <a class="dropdown-item" href="{% url 'account_logout' %}">Выйти</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Вход/выход</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>


        <!-- Page Content -->
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    {% block content %} {{ flatpage.content }} {% endblock content %}
                </div>
            </div>
        </div>
        <!-- Footer -->
<footer style="background-color: khaki; flex-shrink: 0; padding: 20px;">
    <div class="container">
        <div class="text-center">
            <p>Сделано для игроманов</p>
        </div>
    </div>
</footer>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery.slim.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

templates/delete_publication.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Delete{% endblock title %}

{% block content %}
    <br>
    <h3>Удаление объявления:</h3><br>

    {% autoescape off %}
    <h2>{{ post.title }}</h2>
    <span>{{ post.text }}<br></span>
    {% endautoescape %}
    <hr>

    <span>дата публикации: {{ post.dateCreation|date:'d-M-Y f' }}, ({{ post.author }})</span><br>
    <span>Категория: {{ post.get_category_display }}</span>

    <br><br>

    <h4>Подтвердите удаление объявления:</h4>
    <form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-secondary" style="background: red" value="подтвердить"></form>
    <input type=button value="Назад" class="btn btn-secondary" onClick="javascript:history.go(-1);">
{% endblock content %}

templates/edit_publication.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Edit{% endblock title %}
{% load static %}

{% block content %}
    <br>
    <h3>Редактирование объявления:</h3><br>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
		<input class="btn btn-secondary" type="submit" value="Сохранить">
	</form><br>
    <input type=button value="Назад" class="btn btn-secondary" onClick="javascript:history.go(-1);">
{% endblock content %}

templates/index.html
{% extends 'default.html' %}

{% block title %}Ads{% endblock title %}

{% block content %}
    <br><br>
    {% if posts %}
        {% for post in posts %}
            <a href="/post/{{ post.id }}" style="font-size: 20px;"><b>{{ post.title }}</b></a><br>
            <span style="font-size: 12px;"><b>Автор:  {{ post.author }} |
                Дата публикации: {{ post.dateCreation|date:'d.M.Y' }} г.</b></span><br><br>



        {% endfor %}
    {% else %}
        <br><br>
        <h2>Публикаций нет!</h2>
    {% endif %}

    {% if user.is_authenticated %}
        <br><br><br>
        <a class="btn btn-secondary" href="{% url 'create_ad' %}" role="button">Добавить новое объявление</a>
    {% endif %}
{% endblock content %}

templates/publish_item.html
{% extends 'default.html' %}

{% block title %}Ad{% endblock title %}

{% block content %}
    <br><br>
    {% autoescape off %}
    <h2>{{ post.title }}</h2><br>
    <span>{{ post.text }}<br></span>
    {% endautoescape %}
    <hr>
    <span>Автор: {{ post.author }}</span>
    <span>| Категория: {{ post.get_category_display }}</span>
    <span>| Дата публикации: {{ post.dateCreation|date:'d-M-Y f' }}</span>

    <br><br>

    <a class="btn btn-secondary" href="{% url 'index' %}" role="button">Закрыть</a>
    <a class="btn btn-secondary" href="/post/{{ post.id }}/edit" role="button">Редактировать</a>
    <a class="btn btn-secondary" href="/post/{{ post.id }}/delete" role="button">Удалить</a>

    {% if user.is_authenticated %}
    <br><br>
        {% if respond == "Откликнулся" %}
            <a style="color:red">Вы откликнулись на это объявление.</a><br>
            <a href="{% url 'responses' %}">Посмотреть свои отклики</a>
        {% elif respond == "Мое_объявление" %}
            <a style="color:red">Вы не можете откликнуться на свое объявление.</a><br>
        {% else %}
            <a class="btn btn-secondary" href="/respond/{{ post.id }}" role="button">Откликнуться</a>
        {% endif %}
    {% endif %}
    <br><br>
{% endblock content %}

templates/respond.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Respond{% endblock title %}
{% load static %}

{% block content %}
    <br>
    <h3>Текст отклика:</h3><br>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% bootstrap_form form layout='horizontal' %}
		<input class="btn btn-secondary" type="submit" value="Сохранить">
	</form><br>
    <input type=button value="Назад" class="btn btn-secondary" onClick="javascript:history.go(-1);">
{% endblock content %}

templates/responses.html
{% extends 'default.html' %}
{% load bootstrap4 %}
{% block title %}Responses{% endblock title %}

{% block content %}
    <br>
    <h3>Фильтр откликов на мои объявления:</h3><br>
	<form method="POST">
		{% csrf_token %}
        {{ form }}
		<input class="btn btn-secondary" type="submit" value="Показать">
	</form><br>
    {% if title %}
        <h3>Oтклики на мое объявление</h3>
        <a href="/post/{{ response_post_id }}" style="font-size: 20px;"><b>{{ title }}:</b></a><br>
        {% if filter_responses %}
            {% for response in filter_responses %}
                <a><b>Отклик: </b></a>{{ response.text }}<br>
                <span style="font-size: 12px;"><b>Автор отклика: {{ response.author.username }} |
                    дата публикации отклика: {{ response.dateCreation|date:'d.M.Y' }} г.</b></span><br>
                {% if response.status == False %}
                    <a href="/response/accept/{{ response.id }}" style="font-size: 12px; color:green"><b>принять</b></a>
                    <a>&nbsp;&nbsp;&nbsp;</a>
                    <a href="/response/delete/{{ response.id }}" style="font-size: 12px; color:red"><b>удалить</b></a>
                {% else %}
                    <a style="font-size: 14px; color:green"><b>отклик принят</b></a>
                {% endif %}
                <br><br>
            {% endfor %}
        {% else %}
            <br>
            <h5>Откликов нет!</h5>
        {% endif %}
    {% else %}
        <h3>Oтклики на все мои объявления:</h3>
        {% if filter_responses %}
            {% for response in filter_responses %}
                <a><b>Объявление:</b></a>
                <a href="/post/{{ response.post_id }}" style="font-size: 20px;"><b>{{ response.post.title }}</b></a><br>
                <span style="font-size: 12px;"><b>Дата публикации объявления: {{ response.post.dateCreation|date:'d.M.Y' }} г.</b>
                </span><br>
                <a><b>Отклик: </b></a>{{ response.text }}<br>
                <span style="font-size: 12px;"><b>Автор отклика: {{ response.author.username }} |
                    дата публикации отклика: {{ response.dateCreation|date:'d.M.Y' }} г.</b></span><br>
                {% if response.status == False %}
                    <a href="/response/accept/{{ response.id }}" style="font-size: 12px; color:green"><b>принять</b></a>
                    <a>&nbsp;&nbsp;&nbsp;</a>
                    <a href="/response/delete/{{ response.id }}" style="font-size: 12px; color:red"><b>удалить</b></a>
                {% else %}
                    <a style="font-size: 14px; color:green"><b>отклик принят</b></a>
                {% endif %}
                <br><br>
            {% endfor %}
        {% else %}
            <h5>Откликов нет!</h5>
        {% endif %}
    {% endif %}
    <br><br>
    <h3>Мои отклики на объявления:</h3>
    {% if myresponses %}
        {% for response in myresponses %}
            <a><b>Объявление:</b></a>
            <a href="/post/{{ response.post_id }}" style="font-size: 20px;"><b>{{ response.post.title }}</b></a><br>
            <span style="font-size: 12px;"><b>Автор объявления:  {{ response.post.author.username }} |
                дата публикации объявления: {{ response.post.dateCreation|date:'d.M.Y' }} г.</b></span><br>
            <a><b>Мой отклик:</b></a>
            {{ response.text }}<br>
            <span style="font-size: 12px;"><b>Дата публикации отклика: {{ response.dateCreation|date:'d.M.Y' }} г.</b></span><br>
            {% if response.status == True %}
                <a style="font-size: 14px; color:green"><b>Автор объявления принял отклик!</b></a>
            {% else %}
                <a style="font-size: 14px; color:red"><b>Автор объявления пока не принял отклик!</b></a>
            {% endif %}
        <br><br>
        {% endfor %}
    {% else %}
        <h5>Откликов нет!</h5>
    {% endif %}
{% endblock content %}